meta:
  engine: 4.1.0
points:
  zones:
    matrix:
      anchor:
        shift: [50,-75] # Fix KiCad placement
      columns:
        pinky:
          key:
            spread: 18
          rows:
            bottom:
              row_net: P10
              column_net: P0
            home:
              row_net: P9
              column_net: P0
        ring:
          key:
            spread: 18
            origin: [-12, -19]
            stagger: 16
          rows:
            bottom:
              row_net: P10
              column_net: P1
            home:
              row_net: P9
              column_net: P1
        middle:
          key:
            spread: 18
            stagger: 5
          rows:
            bottom:
              row_net: P10
              column_net: P2
            home:
              row_net: P9
              column_net: P2
        index:
          key:
            spread: 18
            stagger: -6
          rows:
            bottom:
              column_net: P3
              row_net: P10
            home:
              column_net: P3
              row_net: P9
      rows:
        bottom:
          padding: 17
        home:
          padding: 17
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [2, -20]
        rotate: 90
      columns:
        near:
          key:
            splay: -90
            origin: [0,0]
          rows:
            home:
              rotate: -90
              column_net: P4
              row_net: P8

        home:
          key:
            spread: 17
            rotate: 90
            origin: [0,0]
          rows:
            home:
              column_net: P5
              row_net: P7

outlines:
  plate:
    - what: rectangle
      where: true
      asym: source
      size: 18
      corner: 3
    - what: rectangle
      where: true
      asym: source
      size: 14
      bound: false
      operation: subtract
  _pcb_perimeter_raw:
    - what: rectangle
      where: true
      asym: source
      size: 18
      corner: 1
  _polygon:
    - what: polygon # all borders
      operation: stack
      points:
        - ref: thumb_home_home
          shift: [-10,-10]
        - ref: thumb_home_home
          shift: [90,-10]
        - ref: thumb_home_home
          shift: [90,90]
        - ref: thumb_home_home
          shift: [-10,90]
  pcb_perimeter:
    - what: outline # keys
      name: _pcb_perimeter_raw
    - what: outline
      name: _polygon
      operation: add

pcbs:
  seventeeen:
    template: kicad8
    outlines:
      main:
        outline: pcb_perimeter
    footprints:
      keys:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          include_keycap: true
          keycap_width: 17.5
          keycap_height: 16.5
          reversible: true
          hotswap: false
          solder: true
          choc_v2_support: false
      seeed:
        what: ceoloide/seeed_xiao
        where: matrix_index_home
        params:
          reversable: true
        adjust.shift: [0.95u, -0.5u]
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      jlcpcb_order_number_text:
        what: ceoloide/utility_text
        where: matrix_middle_bottom
        params:
          text: JLCJLCJLCJLC
          reversible: true
        adjust:
          shift: [0,-u/2]
      ergogen_logo:
        what: ceoloide/utility_ergogen_logo
        where: matrix_middle_bottom
        params:
          scale: 2.5
          reversible: true
        adjust:
          shift: [0,-1.25u]
