meta:
  engine: 4.1.0

units:
  u: 17
  cx: 17
  cy: 17
  default_spread: 17

points:
  zones:
    matrix:
      # anchor:
      #    shift: [50,-75] # Fix KiCad placement ???
      columns:
        outer:
          key:
            stagger: 0
          rows:
            bottom:
              row_net: P10
              column_net: P0
              skip: true
            home:
              row_net: P9
              column_net: P0
            top:
              row_net: P8
              column_net: P0
            num:
              row_net: P7
              column_net: P0
              skip: true
        pinky:
          key:
            stagger: 0
          rows:
            bottom:
              row_net: P10
              column_net: P1
            home:
              row_net: P9
              column_net: P1
            top:
              row_net: P8
              column_net: P1
            num:
              row_net: P7
              column_net: P1
        ring:
          key:
            origin: [-12, -19]
            stagger: 8
          rows:
            bottom:
              row_net: P10
              column_net: P2
            home:
              row_net: P9
              column_net: P2
            top:
              row_net: P8
              column_net: P2
            num:
              row_net: P7
              column_net: P2
        middle:
          key:
            stagger: 2
          rows:
            bottom:
              row_net: P10
              column_net: P3
            home:
              row_net: P9
              column_net: P3
            top:
              row_net: P8
              column_net: P3
            num:
              row_net: P7
              column_net: P3
        index:
          key:
            stagger: -8
          rows:
            bottom:
              row_net: P10
              column_net: P4
            home:
              row_net: P9
              column_net: P4
            top:
              row_net: P8
              column_net: P4
            num:
              row_net: P7
              column_net: P4
        inner:
          key:
            stagger: 0
          rows:
            bottom:
              column_net: P5
              row_net: P10
            home:
              column_net: P5
              row_net: P9
            top:
              row_net: P8
              column_net: P5
            num:
              row_net: P7
              column_net: P5
      rows:
        bottom:
          padding: 1cx
        home:
          padding: 1cx
        top:
          padding: 1cx
        num:
          padding: 1cx
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [17, -21]
      columns:
        home:
          key:
            spread: 17
            origin: [0,0]
          rows:
            home:
              column_net: P6
              row_net: P7

outlines:
  _pcb_perimeter_raw:
    - what: rectangle
      where: true
      asym: source
      size: 17
      corner: 1
  _polygon:
    - what: polygon # all borders
      operation: stack
      points:
        - ref: thumb_home_home
          shift: [9,-10]
        - ref: thumb_home_home
          shift: [-91,-10]
        - ref: thumb_home_home
          shift: [-91,90]
        - ref: thumb_home_home
          shift: [9,90]
  pcb_perimeter:
    - what: outline
      name: _polygon
    # uncomment to see the overhang
    #- what: outline # keys
    #  name: _pcb_perimeter_raw
    #  operation: add

pcbs:
  seventeeen:
    template: kicad8
    outlines:
      main:
        outline: pcb_perimeter
    footprints:
      keys:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          include_keycap: true
          keycap_width: 16.5
          keycap_height: 16.5
          reversible: true
          hotswap: true
          solder: false
          choc_v2_support: false
          #include_plated_holes: true
        adjust.rotate: 270
      seeed:
        what: ceoloide/seeed_xiao
        where: matrix_pinky_bottom
        params:
          reversable: true
        adjust.shift: [18, -18]
        adjust.rotate: 90
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-3, 0]
          rotate: 90
      jlcpcb_order_number_text:
        what: ceoloide/utility_text
        where: matrix_index_num
        params:
          text: 'seventeeen v0.0\nJLCJLCJLCJLC'
          reversible: true
        adjust:
          shift: [0,u/2+5]
      ergogen_logo:
        what: ceoloide/utility_ergogen_logo
        where: matrix_outer_bottom
        params:
          scale: 2.5
          reversible: true
        adjust:
          shift: [0,-1u]
