meta:
  engine: 4.1.0

units:
  u: 17
  cx: 17
  cy: 17
  default_spread: 17

points:
  zones:
    matrix:
      # anchor:
      #    shift: [50,-75] # Fix KiCad placement ???
      columns:
        outer:
          key:
            stagger: 0
          rows:
            bottom:
              row_net: P3
              column_net: P0
              skip: true
            home:
              row_net: P4
              column_net: P0
            top:
              row_net: P5
              column_net: P0
            num:
              row_net: P6
              column_net: P0
              skip: true
        pinky:
          key:
            stagger: 0
          rows:
            bottom:
              row_net: P3
              column_net: P1
            home:
              row_net: P4
              column_net: P1
            top:
              row_net: P5
              column_net: P1
            num:
              row_net: P6
              column_net: P1
        ring:
          key:
            origin: [-12, -19]
            stagger: 9
          rows:
            bottom:
              row_net: P3
              column_net: P2
            home:
              row_net: P4
              column_net: P2
            top:
              row_net: P5
              column_net: P2
            num:
              row_net: P6
              column_net: P2
        middle:
          key:
            stagger: 2
          rows:
            bottom:
              row_net: P3
              column_net: P10
            home:
              row_net: P4
              column_net: P10
            top:
              row_net: P5
              column_net: P10
            num:
              row_net: P6
              column_net: P10
        index:
          key:
            stagger: -9
          rows:
            bottom:
              row_net: P3
              column_net: P9
            home:
              row_net: P4
              column_net: P9
            top:
              row_net: P5
              column_net: P9
            num:
              row_net: P6
              column_net: P9
        inner:
          key:
            stagger: 0
          rows:
            bottom:
              column_net: P8
              row_net: P3
            home:
              column_net: P8
              row_net: P4
            top:
              row_net: P5
              column_net: P8
            num:
              row_net: P6
              column_net: P8
      rows:
        bottom:
          padding: 1cx
        home:
          padding: 1cx
        top:
          padding: 1cx
        num:
          padding: 1cx
    thumb:
      anchor:
        ref: matrix_inner_bottom
        # shifted inwards to try wider keycaps, like 1.25u or 1.75u
        # if that doesn't pan out, shift outwards
        shift: [-1.5, -17 - 7.5]
      columns:
        home:
          key:
            spread: 17
            origin: [0,0]
          rows:
            home:
              row_net: P6
              column_net: P7

outlines:
  _pcb_perimeter_raw:
    - what: rectangle
      where: true
      asym: source
      size: 17
      corner: 0
  _polygon:
    - what: polygon # all borders
      operation: stack
      points:
        - ref: thumb_home_home
          shift: [10,-9]
        - ref: thumb_home_home
          shift: [-92,-9]
        - ref: thumb_home_home
          shift: [-92,93]
        - ref: thumb_home_home
          shift: [10,93]
  pcb_perimeter:
    - what: outline
      name: _polygon
    # uncomment to see the overhang
    - what: outline # keys
      name: _pcb_perimeter_raw
      operation: add

pcbs:
  seventeeen:
    template: kicad8
    outlines:
      main:
        outline: pcb_perimeter
    footprints:
      keys_normal:
        what: ceoloide/switch_choc_v1_v2
        where: /.*(pinky|ring|middle|index|thumb).*/
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          include_keycap: true
          keycap_width: 17
          keycap_height: 17
          reversible: true
          hotswap: true  # weird rotations can be undone if that'd be toggled
          solder: false
          choc_v2_support: false
          #include_plated_holes: true
      keys_rotated_outer:
        $extends: pcbs.seventeeen.footprints.keys_normal
        where: /.*outer.*/
        adjust.orient: 270
      keys_rotated_inner:
        $extends: pcbs.seventeeen.footprints.keys_normal
        where: /.*inner.*/
        adjust.orient: 90
      diode_normal:
        what: diode
        where: /.*(pinky|ring|middle|index|thumb).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -3]
      diode_rotated_outer:
        $extends: pcbs.seventeeen.footprints.diode_normal
        where: /.*outer.*/
        adjust.orient: 270
      diode_rotated_inner:
        $extends: pcbs.seventeeen.footprints.diode_normal
        where: /.*inner.*/
        adjust.orient: 90
      #helper_via_1:
      #  what: via
      #  where: true
      #  params:
      #    net: "{{row_net}}"
      #  adjust:
      #    shift: [3.5, -3]
      #helper_via_2:
      #  what: via
      #  where: true
      #  params:
      #    net: "{{row_net}}"
      #  adjust:
      #    shift: [0, -3]
      #battery_location_suggestion_1:
      #  what: ceoloide/utility_filled_zone
      #  params:
      #    name: b
      #    fill_type: hatch
      #    points: [[30,-2],[60,-2],[60,10],[30,10]]
      #  where: thumb_home_home
      seeed:
        what: ceoloide/seeed_xiao
        where: thumb_home_home
        params:
          reversable: true
        adjust.shift: [1.5, 21]
        adjust.orient: 90
      mounting_hole_se:
        what: ceoloide/mounting_hole_npth
        where: thumb_home_home
        adjust.shift: [10 - 2, -9 + 2]
      mounting_hole_sw:
        what: ceoloide/mounting_hole_npth
        where: thumb_home_home
        adjust.shift: [-92 + 2, -9 + 2]
      mounting_hole_nw:
        what: ceoloide/mounting_hole_npth
        where: thumb_home_home
        adjust.shift: [-92 + 2, 93 - 2]
      mounting_hole_ne:
        what: ceoloide/mounting_hole_npth
        where: thumb_home_home
        adjust.shift: [10 - 2, 93 - 2]
      name_version:
        what: ceoloide/utility_text
        where: matrix_index_num
        params:
          text: 'seventeeen v0.2'
          reversible: true
          width: 1.25
          height: 1.25
        adjust:
          shift: [0,u/2+8]
      jlcpcb_order_number_text:
        what: ceoloide/utility_text
        where: matrix_index_num
        params:
          text: 'JLCJLCJLCJLC'
          width: 1.25
          height: 1.25
          #reversible: true
        adjust:
          shift: [0,u/2+6]

