M48
; DRILL file {KiCad 9.0.2} date 2025-06-22T13:00:46+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-22T13:00:46+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X50.0Y-93.0
X66.0Y-97.0
X66.0Y-113.0
T2
X21.5Y-36.5
X21.5Y-80.5
X42.25Y-16.0
X112.5Y-16.0
X112.5Y-113.0
M30
