name: test

on:
  pull_request:
  push:

jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build
      - run: nix develop -c sh -c 'make -j4'
      - name: Compare results
        run: |
          diff -ur result out \
          || nix run 'nixpkgs#diffoscopeMinimal' \
             -- --exclude-directory-metadata=yes result out
      - run: nix flake check
      - uses: actions/upload-artifact@v4
        with:
          name: seventeeen
          if-no-files-found: error
          path: |
            out/previews/back.svg
            out/previews/front.svg
            out/pcbs/seventeeen.kicad_pcb
            out/fab.zip
